import sys, io, re
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

src_path = 'D:/thayhai/banhang/nopcommerce_schema_data_ready.sql'
out_path = 'D:/thayhai/banhang/nopcommerce_final.sql'

with open(src_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

total = len(lines)
print(f"Source lines: {total}")

# === Identify sections (0-indexed) ===
# Schema: lines 0-2664 (1-2665)
SCHEMA_END = 2665           # exclusive: lines[:2665]
FMT1_DATA_START = 2665      # 'SET IDENTITY_INSERT [dbo].[ActivityLog] ON' at line 2666
FMT1_DATA_END = 58986       # 'SET IDENTITY_INSERT [dbo].[Warehouse] OFF' at line 58986
SCHEMA2_START = 58986       # indexes, FKs, etc.
SCHEMA2_END = 60792         # ends at 'sp_MSforeachtable NOCHECK CONSTRAINT ALL'
FMT2_DATA_START = 60792     # sp_generate_inserts section
FMT2_DATA_END = total

# Tables in format 1 (already identified: 66 tables)
fmt1_tables = set()
for i in range(FMT1_DATA_START, FMT1_DATA_END):
    m = re.search(r'SET IDENTITY_INSERT \[dbo\]\.\[(\w+)\] ON', lines[i])
    if m:
        fmt1_tables.add(m.group(1))
print(f"Format 1 tables: {len(fmt1_tables)}")

# Tables in format 2
fmt2_tables = set()
for i in range(FMT2_DATA_START, FMT2_DATA_END):
    m = re.search(r'SET IDENTITY_INSERT \[dbo\]\.\[(\w+)\] ON', lines[i])
    if m:
        fmt2_tables.add(m.group(1))
print(f"Format 2 tables: {len(fmt2_tables)}")

only_in_fmt2 = fmt2_tables - fmt1_tables
print(f"Only in format 2 (will include): {len(only_in_fmt2)}")
print(f"  {sorted(only_in_fmt2)}")

# === Build output ===
output = []

# Part 1: Schema (CREATE DATABASE, CREATE TABLE)
output.extend(lines[:SCHEMA_END])
print(f"Schema: {SCHEMA_END} lines")

# Part 2: Format 1 data (all 66 tables, correct CAST datetime format)
output.extend(lines[FMT1_DATA_START:FMT1_DATA_END])
print(f"Format 1 data: lines {FMT1_DATA_START+1}-{FMT1_DATA_END}")

# Part 3: Indexes, FKs, NOCHECK constraint
output.extend(lines[SCHEMA2_START:SCHEMA2_END])
print(f"Indexes/FKs/NOCHECK: lines {SCHEMA2_START+1}-{SCHEMA2_END}")

# Part 4: Format 2 data - ONLY for tables NOT in format 1
# Parse format 2 into table blocks and filter
# Each block starts with sp_generate_inserts comments + SET NOCOUNT ON + SET IDENTITY_INSERT ON
# and ends with GO (after SET NOCOUNT OFF)

fmt2_lines = lines[FMT2_DATA_START:FMT2_DATA_END]

# Find block boundaries for each table in format 2
# A block starts at the sp_generate_inserts comment (-- INSERTs generated...)
# or at SET NOCOUNT ON before SET IDENTITY_INSERT ON
# and ends after the final GO following SET NOCOUNT OFF

# Strategy: scan for SET IDENTITY_INSERT [dbo].[Table] ON
# and collect the surrounding context as a block

# Find the block boundaries by looking for the boilerplate pattern
current_block_start = None
current_table = None
i = 0
fmt2_included = 0
fmt2_skipped = 0
datetime_fixes = 0

while i < len(fmt2_lines):
    line = fmt2_lines[i]

    # Detect start of a new table block
    # Look for sp_generate_inserts comment header
    if "--INSERTs generated by 'sp_generate_inserts'" in line:
        current_block_start = i
        current_table = None

    # Detect which table this block is for
    if current_block_start is not None:
        m = re.search(r'SET IDENTITY_INSERT \[dbo\]\.\[(\w+)\] ON', line)
        if m:
            current_table = m.group(1)

    # Detect end of a block (GO after SET NOCOUNT OFF)
    if line.strip() == 'GO' and current_block_start is not None and current_table is not None:
        # Check if this GO comes after NOCOUNT OFF
        if i > 0 and fmt2_lines[i-1].strip() == '' and i > 1:
            # Look back for NOCOUNT OFF
            for j in range(i-1, max(i-5, -1), -1):
                if 'SET NOCOUNT OFF' in fmt2_lines[j]:
                    # This is the end of the block
                    block_lines = fmt2_lines[current_block_start:i+1]

                    if current_table not in fmt1_tables:
                        # Include this block - it's unique to format 2
                        # Apply datetime fix
                        for bl in block_lines:
                            fixed = re.sub(r',(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+)', r",'\1'", bl)
                            if fixed != bl:
                                datetime_fixes += 1
                            output.append(fixed)
                        fmt2_included += 1
                    else:
                        fmt2_skipped += 1

                    current_block_start = None
                    current_table = None
                    break

    i += 1

print(f"\nFormat 2 blocks included: {fmt2_included}")
print(f"Format 2 blocks skipped (already in fmt1): {fmt2_skipped}")
print(f"Datetime fixes in format 2: {datetime_fixes}")

# Add the final EXEC sp_MSforeachtable CHECK CONSTRAINT at the very end
output.append('\n')
output.append("EXEC sp_MSforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL'\n")
output.append('GO\n')

print(f"\nTotal output lines: {len(output)}")

with open(out_path, 'w', encoding='utf-8') as f:
    f.writelines(output)

print(f"Written to: {out_path}")

# Verify: count IDENTITY_INSERT ON/OFF
on_counts = {}
off_counts = {}
for line in output:
    m = re.search(r'SET IDENTITY_INSERT \[dbo\]\.\[(\w+)\] (ON|OFF)', line)
    if m:
        tbl, state = m.group(1), m.group(2)
        if state == 'ON':
            on_counts[tbl] = on_counts.get(tbl, 0) + 1
        else:
            off_counts[tbl] = off_counts.get(tbl, 0) + 1

mismatches = [(t, on_counts.get(t,0), off_counts.get(t,0))
              for t in set(list(on_counts)+list(off_counts))
              if on_counts.get(t,0) != off_counts.get(t,0)]
if mismatches:
    print(f"\nWARNING - Mismatched ON/OFF: {mismatches}")
else:
    print(f"\nAll {len(on_counts)} IDENTITY_INSERT ON/OFF balanced OK")

# Check for remaining unquoted datetimes
unquoted = sum(1 for line in output if re.search(r',\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}', line))
print(f"Remaining unquoted datetimes: {unquoted}")

# Check for truncated inserts
truncated = sum(1 for line in output if line.rstrip().startswith('INSERT ') and not line.rstrip().endswith(')'))
print(f"Truncated INSERT lines: {truncated}")
